### ISSUE TITLE
`qual-plots`: Specify samples to plot

### ISSUE THREAD

**Issue by thermokarst** [qiime2/q2-dada2#45]
This came up at NH Workshop

**Comment by gregcaporaso** [comment]
This would be really handy - it could default to a random subsample of the total collection of sequences, but an optional parameter could optionally specify which specific sample(s) to include in the plot. This should wait until after the `Index` object is developed, since that will impact how we want to specify sample IDs for this functionality.

**Comment by benjjneb** [comment]
Closing as superseded by the new quality plot in demux
