### ISSUE TITLE
qiime dada2 denoise-paired open up options for percent mismatch and overlap length

### ISSUE THREAD

**Issue by shiffer1** [qiime2/q2-dada2#48]
qiime dada2 denoise-paired has options open for trimming and truncating (as seen below):

qiime dada2 denoise-paired \
     --i-demultiplexed-seqs demux-paired-end.qza \
     --p-trim-left-f 0 \
     --p-trunc-len-f 200 \
     --p-trim-left-r 0 \
     --p-trunc-len-r 200 \
     --o-representative-sequences demux-paired-end.qza \
     --p-n-threads 0  \
     --o-table table-1.qza

However, without the ability to adjust the percent mismatch (set at 0 as default) an overlap it has little use. When trying to join paired ends at 0% mismatch sequences have to be identical to be retained. This value should be something users can change and the default should be something more like 40% (perhaps some discussion would be valuable here). The overlap length is set to 20 as default. This could be a decent value (perhaps some discussion would be valuable here), but it should definitely be something users have access to change. So we need to open up the options to be passed into the qiime dada2 denoise-paired command and change the default for percent mismatch.

**Comment by benjjneb** [comment]
It's important to note that merging in the dada2 pipeline is fundamentally different than merging in other pipelines: In the dada2 pipeline the F/R reads are denoised and merged second, in every other pipeline I'm aware of reads are merged first and denoised second.

So, because dada2 is merging after denoising/error-correction, expecting zero mismatches in the overlap region is reasonable, should be the default, and is the appropriate choice in every dataset I've worked with.

That said, the point about exposing more pipeline options to the q2 plugin is a good one. The merging parameters (n-mismatch-allowed, min-overlap) are possibilities. Even more important perhaps are the chimera removal options.

**Comment by shiffer1** [comment]
Thanks for the comment Ben. I found this was not the case with this particular dataset or at least I lost a large number of sequence pairs at the zero percent mismatch value. On average, how much of your sequences do you lose with a zero mismatch?

**Comment by benjjneb** [comment]
>90% of the **reads** that make it past filtering should end up being successfully merged.

Can you clarify what % of post-filtering reads are making it through merging? And if its <90%, what amplicon you are using and what your truncation lengths were?

**Comment by shiffer1** [comment]
Hello, 
I truncated at 200. No pre-trimming. Went from 5,458 features 5,993,929 total frequency for single read data to 558 features 66,000 total frequency. Do you have any suggestions about those parameters?

**Comment by benjjneb** [comment]
My guess is that your truncated reads are not overlapping sufficiently. What is the primer set for this data?

**Comment by shiffer1** [comment]
This is 16S data I believe V4 515-806 primers. I would have to verify that for sure though.

**Comment by benjjneb** [comment]
If you can share 1 sample worth of data (even a subset of 1 sample) I'd be happy to quickly troubleshoot for you, as it will be easier using the R interface.

**Comment by shiffer1** [comment]
I can certainly try doing that as well. I was curious what you think the problem might be. I can try doing smaller truncation or increasing the overlap. Any other suggestions? Thanks.

**Comment by benjjneb** [comment]
My guess is that your truncated reads are not overlapping sufficiently. You could try increasing the truncation lengths.

But clarifying the primer set and amplicon setup (are primers/barcodes part of the read?) is important here.

**Comment by shiffer1** [comment]
After obtaining this information I know why the pair end sequences did not work. The primers covered the V3 and V4 region and therefore cover a region 465 bp. So with truncation at 200 they would not overlap. This would result in them not having an overlapping region. Perhaps I can try it without the truncation.

**Comment by benjjneb** [comment]
That will do it.

Keep in mind that it is valid to significantly relax the `maxEE` filtering parameter, because dada2 is modeling the quality scores. You are probably going to have to here because 2x250 reads will barely overlap to start with, and very likely the qualities got very low towards the end of the reverse read.

**Comment by benjjneb** [comment]
Closing as assuming solved by fixing the truncation lengths.
