### ISSUE TITLE
Use DADA2 1.4 to fix quality-score precedence bug in parameters

### ISSUE THREAD

**Issue by ebolyen** [qiime2/q2-dada2#56]
It looks like this is up on bioconda, although it lists both `1.4` and `1.4.0` and I haven't had a chance to figure out the difference. 

From a [forum post](https://forum.qiime2.org/t/problem-with-dada2-denoise-paired-command/520/12?u=ebolyen):

> There is a small bug in the 1.2 version of the DADA2 package the plugin is using (minQ is enforced before trimming, rather than after) that is preventing p-trim-left-f from working as expected. So you would need to trim off that bad staring base position with another bit of software to get it to work with the current QIIME2 plugin. When the plugin upgrades to the 1.4 version of DADA2 the p-trim-left-f approach should work.

The conda-recipe pins the version to 1.2 so this will need to wait until 2017.5 unless we want to patch.

@benjjneb would it be more appropriate to list our dependency as `>= 1.2` (or rather `>= 1.4` now) so that just upgrading `dada2` fixes these kinds of issues?

**Comment by benjjneb** [comment]
My concern about removing the fixed version dependence is that I haven't guaranteed that the current q2-dada2 R scripts are robust to all default parameter changes, and there were 2 defaults changed in our 1.4 release.

I think this bug is sufficiently minor to leave until another release of the plugin, at which point it might be worth reviewing the R code and explicitly defining every parameter to allow for `>= 1.4` dependencies in the future.

**Comment by ebolyen** [comment]
fixed by #61
